#%RAML 0.8
title: Sample API
version: v1
documentation:
  - title: Sample Documentation 1
    content: !include documentation-1.md
  - title: Sample Documentation 2
    content: !include documentation-2.md
/gists:
  displayName: Gists
  description: !include gist-description.md
  /public:
    displayName: Public Gists
    description: Public gists (description)
    /{gistId}:
      displayName: Public Gist
      description: Individual public gist
      uriParameters:
        gistId:
          displayName: Gist ID
          description: The ID of the Gist
          type: integer
