#%RAML 0.8
title: Sample API
version: v1
documentation:
  - title: Sample Documentation 1
    content: !include documentation-1.md
  - title: Sample Documentation 2
    content: !include documentation-2.md
/gists:
  displayName: Gists
  /public:
    displayName: Public Gists
