#%RAML 0.8
title: Sample API
version: v1
documentation:
  - title: Sample Documentation 1
    content: !include documentation-1.md
  - title: Sample Documentation 2
    content: !include documentation-2.md
/gists:
  displayName: Gists
  description: !include gist-description.md
  get:
    displayName: Get a list of Gists
    description: |
      Get a list of Gists. And do **other stuff**
    body:
      application/json:
        schema: |
          {
            "$schema": "http://json-schema.org/draft-03/schema",
            "properties": {
                "input": {
                    "required": false,
                    "type": "string"
                }
            },
            "required": false,
            "type": "object"
          }
  post:
    displayName: Create a new Gist
  /public:
    displayName: Public Gists
    description: Public gists (description)
    /{gistId}:
      displayName: Public Gist
      description: Individual public gist
      uriParameters:
        gistId:
          displayName: Gist ID
          description: The ID of the Gist
          type: integer
